apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::719742385367:role/eksctl-ecommerce-cluster-nodegroup-NodeInstanceRole-e6jcTcJmVNbL
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::719742385367:role/CodeBuildEcommerceRole
      username: codebuild
      groups:
        - system:masters
