version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ap-south-1"
    CLUSTER_NAME: "ecommerce-cluster"  
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Install kubectl"
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl && mv kubectl /usr/local/bin/
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo "Configure kubeconfig"
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_DEFAULT_REGION
      - kubectl version --client
      - ls -la
  build:
    commands:
      - echo "Read images.json and replace images in manifests"
      - cat images.json
      - python - <<'PY'
import json,subprocess,sys
with open('images.json') as f:
    imgs=json.load(f)
for obj in imgs:
    svc=obj['service']
    image=obj['image']
    print("Updating manifests for", svc, image)
    # This assumes image lines in k8s-manifests contain the service name
    subprocess.run(["bash","-c",f"grep -RIl \"{svc}\" k8s-manifests | xargs -r sed -i 's|image:.*{svc}.*|image: {image}|g'"])
# Apply manifests to ecommerce namespace (ensure namespace exists)
subprocess.run(["kubectl","apply","-f","k8s-manifests/"])
PY
