apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: docker.io/sukhman78/ecommerce-test:ecommerce-test-discovery-service
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
