server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: always
    prometheus:
      access: read-only
  metrics:
    enable:
      http: true
      jvm: true
      logback: true
      system: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active:default}
  prometheus:
    metrics:
      export:
        enabled: true
        step: 1m
